### ISSUE TITLE
AUCMLoss does not use margin argument

### ISSUE THREAD

**Issue by ayhyap** [yzhuoning/LibAUC#2]
I noticed in the AUCMLoss class that the margin argument is not used.
Following the formulation in the paper, the forward function should be changed in line 20 from
`2*self.alpha*(self.p*(1-self.p) + \`
to
`2*self.alpha*(self.p*(1-self.p)*self.margin + \`

**Comment by yzhuoning** [comment]
When updating parameters, we manually compute the gradient w.r.t. `alpha` including margin `m` according to the `eqn(9)` instead of using `autograd` by the above formulation. I will make some changes to avoid confusion in the next update of our library. Thanks!
