### ISSUE TITLE
Using AUCMLoss with imratio>1

### ISSUE THREAD

**Issue by ayhyap** [yzhuoning/LibAUC#3]
I'm not very familiar with the maths in the paper so please forgive me if i'm asking something obvious.

The AUCMLoss uses the "imbalance ratio" between positive and negative samples.
The ratio is defined as 
> the ratio of # of positive examples to the # of negative examples

Or `imratio=#pos/#neg`

When #pos<#neg, imratio is some value between 0 and 1.
But when #pos>#neg, imratio>1

Will this break the loss calculations? I have a feeling it would invalidate the many `1-self.p` calculations in the LibAUC implementation, but as i'm not familiar with the maths I can't say for sure.

Also, is there a problem (mathematically speaking) with calculating `imratio=#pos/#total_samples`, to avoid the problem above?
When #pos<<#neg, #neg approximates #total_samples.

**Comment by yzhuoning** [comment]
Hi, 

In fact, this is a typo in the paper. The correct definition of imbalance ratio should be `#pos_samples/#total_samples` (aka `p`) and the value of  `p` is  between [0,1].  Here, positive class is also referred to as minority class, so you can always mark the minority samples as positive in your own datasets, which shouldn't affect your training process. 

Hope it helps! 

Thanks.
