### ISSUE TITLE
Only compatible with Nvidia GPU

### ISSUE THREAD

**Issue by Beckham45** [yzhuoning/LibAUC#6]
I tried running the example tutorial but I got the following error.
'''
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
'''

**Comment by yzhuoning** [comment]
Hi, please try to install the latest version (1.1.4). You should be able to run the example code (e.g., remove lines with `.cuda()`) on CPU.

**Comment by Beckham45** [comment]
Thank you for the fix.
Can it be modified to also work for TensorFlow just as well?
