### ISSUE TITLE
When to use retain_graph=True?

### ISSUE THREAD

**Issue by dfrahman** [yzhuoning/LibAUC#9]
Hi,

When to use retain_graph=True in the loss backward function?

In 2 examples (2 and 4), it is True. But not in the other examples.

I appreciate your time.

**Comment by yzhuoning** [comment]
Hi, you can ignore this parameter.  `retain_graph=True` is usually required when computing 2nd gradient. I will remove this parameter in the tutorial as well. Thanks!
